LAND_USES = ["AGR", "COM", "FOR", "OPS", "PUB", "RES", "TRA"]
POLLUTANTS = [
    "TSS",
    "TP",
    "NO3",
    "NH3",
    "PB",
    "CU",
    "ZN",
    "BOD",
    "E.COLI",
    "GLYPHOSATE",
    "2,4-D",
    "CARBARYL",
    "OIL&GREASE",
]
BMPS = [
    "Nutrient Management Plan - Agriculture",
    "Nutrient Management Plan - Urban",
    "Integrated Pest Management",
    "Incentive Program",
    "Conservation Buffer",
    "Conservation Cover",
    "Grass Border",
    "Buffer/Filter Strip",
    "Riparian Buffer",
    "Critical Area Planting",
    "Streamside Management Area",
    "Water Quality Basins",
    "Bioretention/Biofilters",
    "Media Filter",
    "Impervious Area Reduction",
    "Organic Farming",
    "Drinking Water Protection Zones",
    "Emergency Response Plan",
    "No-Till or Reduced Till",
    "Cover Crops",
]
SUBBASINS = [
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    201,
    202,
    203,
    204,
    205,
    301,
    302,
    303,
    304,
    305,
    306,
    401,
    402,
    403,
    404,
    405,
    406,
    501,
    502,
    503,
    601,
    602,
    603,
    604,
    605,
    606,
    607
]

